spring.application.name=training
spring.datasource.url=jdbc:mysql://localhost:3306/sjcoders_training
spring.datasource.username=root
spring.datasource.password=Admin@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG